networks:
  karpenko_net:
    external: true

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://${VPS_IP}:8080/api/v1
    container_name: karpenko_frontend
    restart: unless-stopped
    environment:
      API_URL_INTERNAL: http://karpenko_backend:4000/api/v1
    ports:
      - "3000:3000"
    networks:
      - karpenko_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
